# Generated by Django 5.0.3 on 2024-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=255)),
                ('absence_date', models.DateField()),
                ('absence_reason', models.CharField(choices=[('AW', 'Accident at Work'), ('BH', 'Bank Holiday'), ('BV', 'Bereavement'), ('CO', 'College'), ('DL', 'Dependent Leave'), ('DR', 'Doctors/Dentists'), ('HP', 'Holiday Paid'), ('HO', 'Hospital'), ('JU', 'Jury Service'), ('MA', 'Maternity Leave'), ('NS', 'Non Sickness Absence'), ('PA', 'Paternity Leave'), ('SA', 'Sickness Absence'), ('TR', 'Training'), ('UA', 'Unauthorised Absence')], max_length=2)),
            ],
        ),
    ]
